Updating config to match cop changes
After updating the rubop gem, got this output:

``
(master)$ be rubocop
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Style/ClassAndModuleCamelCase has the wrong namespace - should be Naming
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Style/ConstantName has the wrong namespace - should be Naming
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Style/FileName has the wrong namespace - should be Naming
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Lint/ConditionPosition has the wrong namespace - should be Layout
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
/Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml: Lint/EndAlignment has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in /Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml, please update it)
The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
(obsolete configuration found in /Users/arcadia/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rubocop-10208e751dd2/config/enabled.yml, please update it)
```